name: CI

on: pull_request

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v2

      - uses: sdkman/sdkman-action@master
        with:
          candidate: gradle
          version: 6.7.1
          
      - uses: fwilhe2/setup-kotlin@main
        with:
          install-native: true
          version: 1.4.20
        
      - uses: actions/setup-node@v2
        with:
          node-version: '10'
          
      - name: Install Danger JS
        run: npm install -g danger
         
      - run: sudo chmod -R a+rwx /usr/local/
       
      - name: Install Danger Kotlin
        run: make install
         
      - name: Run tests
        run: gradle danger-kotlin-library:test
      
      - name: Run Danger-Kotlin
        run: DEBUG='*' danger-kotlin ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
